version: '3'


services:
  mariadb:
    container_name: mariadb
    image: chephei/maria:1.0
    restart: unless-stopped
    env_file:
      - ./src/.env
    ports: ['3306:3306']
    volumes:
      - ./data/mysql/dump:/dump
      - ./data/mysql/mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      ce_front:
        ipv4_address: 192.168.11.2
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  nodejs:
    container_name: nodejs
    image: chephei/nodejs:1.0
    restart: unless-stopped
    env_file:
      - ./src/.env
    ports: ['3000:3000']
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      ce_front:
        ipv4_address: 192.168.11.3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  python:
    container_name: python
    image: chephei/python:1.0
    restart: unless-stopped
    env_file:
      - ./src/.env
    ports: ['8800:8800']
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      ce_front:
        ipv4_address: 192.168.11.4
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

networks:
  ce_front:
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
          ip_range: 192.168.11.2/28
