FROM node:lts-alpine3.16

WORKDIR /srv

# COPY ./frontend/package*.json ./
# COPY ./frontend/yarn.lock ./
# COPY ./frontend/public ./
# COPY ./frontend/src ./

COPY ./frontend ./

RUN npm install yarn

RUN ls -l /srv/*

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
