FROM alpine:3.16

RUN apk add --no-cache mariadb \
    mariadb-client mariadb-server-utils \
    pwgen rsync && \
    rm -f /var/cache/apk/*

ADD ./docker/files/run_maria.sh /scripts/run.sh
RUN mkdir /docker-entrypoint-initdb.d && \
    mkdir /scripts/pre-exec.d && \
    mkdir /scripts/pre-init.d && \
    chmod -R 755 /scripts

ADD ./docker/files/schema.sql /docker-entrypoint-initdb.d/schema.sql

EXPOSE 3306

VOLUME ["/var/lib/mysql"]

ENTRYPOINT ["/scripts/run.sh"]
