apiVersion: apps/v1
kind: Deployment
metadata:
  name: python_reactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python_reactjs
  template:
    metadata:
      labels:
        app: python_reactjs
    spec:
      containers:
        - name: mariadb
          image: chephei/maria:1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: python
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_DATABASE
              value: vasco
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: root-password
          volumeMounts:
            - name: mysql-dump
              mountPath: /dump
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: '0.5'
              memory: 256Mi

        - name: nodejs
          image: chephei/nodejs:1.0
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              cpu: '0.5'
              memory: 256Mi

        - name: python
          image: chephei/python:1.0
          ports:
            - containerPort: 8800
          env:
            - name: PYTHON_ENV
              value: production
          resources:
            limits:
              memory: 256Mi
              cpu: '1'
            requests:
              cpu: '0.5'
              memory: 128Mi

  volumes:
    - name: mysql-dump
      emptyDir: {}
    - name: mysql-data
      emptyDir: {}
